configfile: "config/config.yaml"

FILENAMES = ['A','B','C']
DATA_DIR = config['data_dir']
OUTPUTS_DIR = config['outputs_dir']

rule all:
	input:
		expand("{OUTPUTS_DIR}/wc_all.png", OUTPUTS_DIR=OUTPUTS_DIR)

rule count:
	input:
		expand("{DATA_DIR}/{filename}.txt", DATA_DIR=DATA_DIR, filename=FILENAMES)
	output:
		"temp/wc_{filename}.txt"
	shell:
		"wc -w {input} > {output}"

rule concat:
	input:
		"temp/wc_{filename}.txt"
	output:
		"temp/wc_all.csv"
	script:
		"scripts/concat.py"

rule plot:
	input:
		"temp/wc_all.csv"
	output:
		expand("{OUTPUTS_DIR}/wc_all.png", OUTPUTS_DIR=OUTPUTS_DIR)
	script:
		"scripts/plot.py"

